# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='some_string', max_length=255),
        ),
    ]
