# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_auto_20170130_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
